### ISSUE TITLE
Tornado server error 

### ISSUE THREAD

**Issue by AsMoh** [victorssilva/simplecv-mobile-camera#18]
Hi,

I am new to tornado and I want to make a python server using tornado .

Actually, I want to make an android app that makes beautiful effects on images using SimpleCV. I found this app http://github.com/victsou/simplecv-mobile-camera. I have windows7 , and I have installed tornado in my laptop. when I try to test the app on my android device, I get this error( see the attached image plz).

 I tried a lot to make work to start working on my app , but I could not 

Can you help me to know why I am getting this error, please? Thank you so much.
![whyerror](https://cloud.githubusercontent.com/assets/10277729/5535308/07272984-8a95-11e4-868a-1b750be093c5.jpg)

**Comment by victorssilva** [comment]
None of that code was written with Windows in mind, so it probably has to do with the file paths.

**Comment by AsMoh** [comment]
What do you suggest to fix this error?

**Comment by victorssilva** [comment]
I've never used Windows for any of that stuff, so I don't really know which problems you might encounter; one option is just using Linux...

**Comment by AsMoh** [comment]
I can't install Linux in my laptop. But, can I ask you some questions , please?  I  changed the http://10.0.2.2:8000 to my local ip adresse http://192.168.1.110:8000 in the app  and the server. Is this correct?
Also, when I was watching your video, I noticed that your tornado server is inside the android project , ~/dev/Android/workspace/simplecv-mobile-camera/web-server
Is this necessary?? I put the web server inside C:\Python27 . Thank you so much.

**Comment by victorssilva** [comment]
I don't recall these details exactly, but if I'm not mistaken it's just a matter of accessing localhost from within the emulator - you'll have to do some research on that.

The path where you place the server shouldn't be a problem (unless I did something stupid), as long as the structure inside it remains.
